spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    compatibility-verifier:
      enabled: "true"
    config:
      server:
        native:
          search-locations: "classpath:/config"

server:
  port: 8071

  cloud:
    compatibility-verifier:
      enabled: "false"