spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    compatibility-verifier:
      enabled: "true"
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:C:/Users/Innocent Udo/MICROSERVICES_AND_SPRING-CLOUD/Section5-6/config"

server:
  port: 8071

  cloud:
    compatibility-verifier:
      enabled: "false"