spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    compatibility-verifier:
      enabled: "true"
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:C:/Users/Innocent Udo/MICROSERVICES_AND_SPRING-CLOUD/Section5-6/config"
        git:
          uri: "https://github.com/Innocentsax/CLOUD_CONFIGS.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071

  cloud:
    compatibility-verifier:
      enabled: "false"