# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loan-deployment
serviceName: loan
appLabel: loan
appName: loan

replicaCount: 1

image:
  repository: innocentudo/loan
  tag: s14

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false