services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 54175:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h","localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  carddb:
    image: mysql
    container_name: carddb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h","localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carddb
    extends:
      file: common-config.yml
      service: network-deploy-service

  loandb:
    image: mysql
    container_name: loandb
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h","localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loandb
    extends:
      file: common-config.yml
      service: network-deploy-service


  configserver:
    image: "innocentudo/configserver:s6"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    image: "innocentudo/accounts:s6"
    container_name: account_ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:54175/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loan:
    image: "innocentudo/loan:s6"
    container_name: loan_ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loan"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3308/loandb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  card:
    image: "innocentudo/card:s6"
    container_name: card_ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "card"
      SPRING_DATASOURCE_URL: "jdbc:mysql://carddb:3307/carddb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  innocentudo:
    driver: "bridge"