server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to InnocentUdo's accounts related local APIs"
  contactDetails:
    name: "Innocent Udo -Developer"
    email: "innocentcharlesudo@gmail.com"
  onCallSupport:
      -(+234)8163093928
      -(+234)7036578340