{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
          {{- if .Values.appname_enabled }}
          - name: SPRING_APPLICATION_NAME
            value: {{ .Values.appName }}
          {{- end }}
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILES_ACTIVE
          {{- end }}
          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CONFIG_IMPORT
          {{- end }}
          {{- if .Values.eureka_enabled }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          {{- end }}
          {{- if .Values.resouceserver_enabled }}
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          {{- end }}
          {{- if .Values.otel_enabled }}
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: JAVA_TOOL_OPTIONS
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_EXPORTER_OTLP_ENDPOINT
          - name: OTEL_METRICS_EXPORTER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_METRICS_EXPORTER
          - name: OTEL_SERVICE_NAME
            value: {{ .Values.appName }}
          {{- end }}
          {{- if .Values.kafka_enabled }}
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          {{- end }}

  {{- end -}}